# copied in from configs

# project definitions
project: doc
audience: non-coders
product: all
platform: all
version: all
destination: ../doc_non-coders
topnav_title: corpkit
homepage_title: corpkit&#58; corpus linguistics software
site_title: corpkit
disqus_shortname: mcdonaldd
google_analytics: 

# variables

sidebar_tagline: non-coders
sidebar_version: version 1.xx
theme_file: theme-green.css
project_file_name: doc

port: 4003
exclude:
  - doc_geeks*
  - configs/
  - _site
  - _drafts
  - di_multi*

# same for all
host: 127.0.0.1
feedback_email: mcdonaldd@unimelb.edu.au
sidebar_accordion: true
markdown: redcarpet
print: false

# only use suffix if you need to force index.html to display
# suffix: index.html

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "tables", "with_toc_data"]

highlighter: pygments

collections:
  tooltips:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true


