destination: ../doc_writers-pdf
url: "http://127.0.0.1:4004"
baseurl: "/doc_writers"
port: 4004
print: true
print_title: corpkit for non-coders
print_subtitle: graphical interface
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true